### ISSUE TITLE
Cannot start container properly on Windows and Linux

### ISSUE THREAD

**Issue by j-maas** [benhutchins/docker-taiga-example#10]
I have tremendous difficulties in trying to make this run on Windows 10.

The first problem is that `postgres` does not like to map volumes on Windows. While executing `docker-compose up` inside the fresh `docker-taiga-example/simple` folder, it complains about ownership:
```postgres_1  | The files belonging to this database system will be owned by user "postgres".
postgres_1  | This user must also own the server process.
```
Googling this identifies the issue with `postgres` and Windows. I worked around this by changing the `postgres`'s volume from
```
    volumes:
      - ./pgdata:/var/lib/postgresql/data
```
to
```
    volumes:
      - /var/lib/postgresql/data
```

Then, usually the startup with `docker-compose up` still fails and hangs:
```
$ docker-compose up
Creating network "simple_default" with the default driver
Creating simple_postgres_1
Creating simple_taiga_1
Attaching to simple_postgres_1, simple_taiga_1
postgres_1  | The files belonging to this database system will be owned by user "postgres".
postgres_1  | This user must also own the server process.
postgres_1  |
taiga_1     | Running database check
postgres_1  | The database cluster will be initialized with locale "en_US.utf8".
postgres_1  | The default database encoding has accordingly been set to "UTF8".
postgres_1  | The default text search configuration will be set to "english".
postgres_1  |
postgres_1  | Data page checksums are disabled.
postgres_1  |
postgres_1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres_1  | creating subdirectories ... ok
postgres_1  | selecting default max_connections ... 100
postgres_1  | selecting default shared_buffers ... 128MB
postgres_1  | selecting dynamic shared memory implementation ... posix
postgres_1  | creating configuration files ... ok
postgres_1  | running bootstrap script ... ok
postgres_1  | performing post-bootstrap initialization ... ok
postgres_1  | syncing data to disk ...
postgres_1  | WARNING: enabling "trust" authentication for local connections
postgres_1  | You can change this by editing pg_hba.conf or using the option -A, or
postgres_1  | --auth-local and --auth-host, the next time you run initdb.
postgres_1  | ok
postgres_1  |
postgres_1  | Success. You can now start the database server using:
postgres_1  |
postgres_1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres_1  |
postgres_1  | waiting for server to start....LOG:  database system was shut down at 2017-04-29 15:39:24 UTC
postgres_1  | LOG:  MultiXact member wraparound protections are now enabled
postgres_1  | LOG:  database system is ready to accept connections
postgres_1  | LOG:  autovacuum launcher started
postgres_1  |  done
postgres_1  | server started
taiga_1     | Connecting to database:
taiga_1     | dbname='taigadb' user='taiga' host='postgres' password='password'
taiga_1     | Traceback (most recent call last):
taiga_1     |   File "/checkdb.py", line 14, in <module>
taiga_1     |     conn = psycopg2.connect(conn_string)
taiga_1     |   File "/usr/local/lib/python3.5/site-packages/psycopg2/__init__.py", line 164, in connect
taiga_1     |     conn = _connect(dsn, connection_factory=connection_factory, async=async)
taiga_1     | psycopg2.OperationalError: could not connect to server: Connection refused
taiga_1     |   Is the server running on host "postgres" (172.18.0.2) and accepting
taiga_1     |   TCP/IP connections on port 5432?
taiga_1     |
taiga_1     | Failed to connect to database server or database does not exist.
postgres_1  | CREATE DATABASE
postgres_1  |
postgres_1  | CREATE ROLE
postgres_1  |
postgres_1  |
postgres_1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres_1  |
postgres_1  | LOG:  received fast shutdown request
postgres_1  | waiting for server to shut down...LOG:  aborting any active transactions
postgres_1  | LOG:  autovacuum launcher shutting down
postgres_1  | .LOG:  shutting down
postgres_1  | LOG:  database system is shut down
simple_taiga_1 exited with code 1
postgres_1  |  done
postgres_1  | server stopped
postgres_1  |
postgres_1  | PostgreSQL init process complete; ready for start up.
postgres_1  |
postgres_1  | LOG:  database system was shut down at 2017-04-29 15:39:26 UTC
postgres_1  | LOG:  MultiXact member wraparound protections are now enabled`
postgres_1  | LOG:  database system is ready to accept connections
postgres_1  | LOG:  autovacuum launcher started
```
I can get around this issue by killing the hanging processes, deleting the host folder `docker-taiga-example/simple/media` created in the previous startup and rerunning `docker-compose up`:
```
$ docker-compose up
Starting simple_postgres_1
Starting simple_taiga_1
Attaching to simple_postgres_1, simple_taiga_1
postgres_1  | LOG:  database system was shut down at 2017-04-29 15:49:35 UTC
postgres_1  | LOG:  MultiXact member wraparound protections are now enabled
postgres_1  | LOG:  database system is ready to accept connections
taiga_1     | Running database check
postgres_1  | LOG:  autovacuum launcher started
taiga_1     | Connecting to database:
taiga_1     | dbname='taigadb' user='taiga' host='postgres' password='password'
taiga_1     | Database does not appear to be setup.
taiga_1     | Configuring initial database
taiga_1     | Operations to perform:
taiga_1     |   Apply all migrations: users, sessions, userstorage, notifications, webhooks, contenttypes, references, milestones, votes, github, likes, auth, tasks, custom_attributes, attachments, timeline, history, gogs, gitlab, issues, djmail, projects, admin, userstories, external_apps, wiki, bitbucket, easy_thumbnails, epics, feedback, taiga_contrib_slack
taiga_1     | Running migrations:
taiga_1     |   Rendering model states... DONE
taiga_1     |   Applying contenttypes.0001_initial... OK
taiga_1     |   Applying users.0001_initial... OK
taiga_1     |   Applying admin.0001_initial... OK
taiga_1     |   Applying admin.0002_logentry_remove_auto_add... OK
taiga_1     |   Applying users.0002_auto_20140903_0916... OK
taiga_1     |   Applying projects.0001_initial... OK
taiga_1     |   Applying projects.0002_auto_20140903_0920... OK
taiga_1     |   Applying attachments.0001_initial... OK
taiga_1     |   Applying attachments.0002_add_size_and_name_fields... OK
taiga_1     |   Applying attachments.0003_auto_20150114_0954... OK
taiga_1     |   Applying attachments.0004_auto_20150508_1141... OK
taiga_1     |   Applying attachments.0005_attachment_sha1... OK
taiga_1     |   Applying attachments.0006_auto_20160617_1233... OK
taiga_1     |   Applying contenttypes.0002_remove_content_type_name... OK
taiga_1     |   Applying auth.0001_initial... OK
taiga_1     |   Applying auth.0002_alter_permission_name_max_length... OK
taiga_1     |   Applying auth.0003_alter_user_email_max_length... OK
taiga_1     |   Applying auth.0004_alter_user_username_opts... OK
taiga_1     |   Applying auth.0005_alter_user_last_login_null... OK
taiga_1     |   Applying auth.0006_require_contenttypes_0002... OK
taiga_1     |   Applying auth.0007_alter_validators_add_error_messages... OK
taiga_1     |   Applying users.0003_auto_20140903_0925... OK
taiga_1     |   Applying users.0004_auto_20140913_1914... OK
taiga_1     |   Applying users.0005_alter_user_photo... OK
taiga_1     |   Applying users.0006_auto_20141030_1132... OK
taiga_1     |   Applying bitbucket.0001_initial... OK
taiga_1     |   Applying milestones.0001_initial... OK
taiga_1     |   Applying issues.0001_initial... OK
taiga_1     |   Applying userstories.0001_initial... OK
taiga_1     |   Applying userstories.0002_auto_20140903_1301... OK
taiga_1     |   Applying userstories.0003_userstory_order_fields... OK
taiga_1     |   Applying userstories.0004_auto_20141001_1817... OK
taiga_1     |   Applying userstories.0005_auto_20141009_1656... OK
taiga_1     |   Applying userstories.0006_auto_20141014_1524... OK
taiga_1     |   Applying userstories.0007_userstory_external_reference... OK
taiga_1     |   Applying userstories.0008_auto_20141210_1107... OK
taiga_1     |   Applying userstories.0009_remove_userstory_is_archived... OK
taiga_1     |   Applying projects.0003_auto_20140913_1710... OK
taiga_1     |   Applying projects.0004_auto_20141002_2337... OK
taiga_1     |   Applying projects.0005_membership_invitation_extra_text... OK
taiga_1     |   Applying notifications.0001_initial... OK
taiga_1     |   Applying history.0001_initial... OK
taiga_1     |   Applying history.0002_auto_20140916_0936... OK
taiga_1     |   Applying history.0003_auto_20140917_1405... OK
taiga_1     |   Applying history.0004_historyentry_is_hidden... OK
taiga_1     |   Applying notifications.0002_historychangenotification... OK
taiga_1     |   Applying notifications.0003_auto_20141029_1143... OK
taiga_1     |   Applying notifications.0004_watched... OK
taiga_1     |   Applying userstories.0010_remove_userstory_watchers... OK
taiga_1     |   Applying userstories.0011_userstory_tribe_gig... OK
taiga_1     |   Applying tasks.0001_initial... OK
taiga_1     |   Applying tasks.0002_tasks_order_fields... OK
taiga_1     |   Applying tasks.0003_task_external_reference... OK
taiga_1     |   Applying tasks.0004_auto_20141210_1107... OK
taiga_1     |   Applying tasks.0005_auto_20150114_0954... OK
taiga_1     |   Applying tasks.0006_auto_20150623_1923... OK
taiga_1     |   Applying tasks.0007_auto_20150629_1556... OK
taiga_1     |   Applying tasks.0008_remove_task_watchers... OK
taiga_1     |   Applying tasks.0009_auto_20151104_1131... OK
taiga_1     |   Applying users.0007_auto_20150209_1611... OK
taiga_1     |   Applying users.0008_auto_20150213_1701... OK
taiga_1     |   Applying users.0009_auto_20150326_1241... OK
taiga_1     |   Applying users.0010_auto_20150414_0936... OK
taiga_1     |   Applying timeline.0001_initial... OK
taiga_1     |   Applying projects.0006_auto_20141029_1040... OK
taiga_1     |   Applying projects.0007_auto_20141024_1011... OK
taiga_1     |   Applying projects.0008_auto_20141024_1012... OK
taiga_1     |   Applying projects.0009_auto_20141024_1037... OK
taiga_1     |   Applying projects.0010_project_modules_config... OK
taiga_1     |   Applying projects.0011_auto_20141028_2057... OK
taiga_1     |   Applying projects.0012_auto_20141210_1009... OK
taiga_1     |   Applying projects.0013_auto_20141210_1040... OK
taiga_1     |   Applying projects.0014_userstorystatus_is_archived... OK
taiga_1     |   Applying projects.0015_auto_20141230_1212... OK
taiga_1     |   Applying projects.0016_fix_json_field_not_null... OK
taiga_1     |   Applying projects.0017_fix_is_private_for_projects... OK
taiga_1     |   Applying projects.0018_auto_20150219_1606... OK
taiga_1     |   Applying projects.0019_auto_20150311_0821... OK
taiga_1     |   Applying timeline.0002_auto_20150327_1056... OK
taiga_1     |   Applying timeline.0003_auto_20150410_0829... OK
taiga_1     |   Applying timeline.0004_auto_20150603_1312... OK
taiga_1     |   Applying projects.0020_membership_user_order... OK
taiga_1     |   Applying projects.0021_auto_20150504_1524... OK
taiga_1     |   Applying projects.0022_auto_20150701_0924... OK
taiga_1     |   Applying projects.0023_auto_20150721_1511... OK
taiga_1     |   Applying projects.0024_auto_20150810_1247... OK
taiga_1     |   Applying projects.0025_auto_20150901_1600... OK
taiga_1     |   Applying projects.0026_auto_20150911_1237... OK
taiga_1     |   Applying projects.0027_auto_20150916_1302... OK
taiga_1     |   Applying projects.0028_project_is_featured... OK
taiga_1     |   Applying projects.0029_project_is_looking_for_people... OK
taiga_1     |   Applying likes.0001_initial... OK
taiga_1     |   Applying projects.0030_auto_20151128_0757... OK
taiga_1     |   Applying projects.0031_project_logo... OK
taiga_1     |   Applying projects.0032_auto_20151202_1151... OK
taiga_1     |   Applying projects.0033_text_search_indexes... OK
taiga_1     |   Applying projects.0034_project_looking_for_people_note... OK
taiga_1     |   Applying projects.0035_project_blocked_code... OK
taiga_1     |   Applying projects.0036_project_transfer_token... OK
taiga_1     |   Applying projects.0037_auto_20160208_1751... OK
taiga_1     |   Applying projects.0038_auto_20160215_1133... OK
taiga_1     |   Applying projects.0039_auto_20160322_1157... OK
taiga_1     |   Applying projects.0040_remove_memberships_of_cancelled_users_acounts... OK
taiga_1     |   Applying projects.0043_auto_20160530_1004... OK
taiga_1     |   Applying projects.0044_auto_20160531_1150... OK
taiga_1     |   Applying projects.0041_auto_20160519_1058... OK
taiga_1     |   Applying projects.0042_auto_20160525_0911... OK
taiga_1     |   Applying projects.0045_merge... OK
taiga_1     |   Applying issues.0002_issue_external_reference... OK
taiga_1     |   Applying issues.0003_auto_20141210_1108... OK
taiga_1     |   Applying issues.0004_auto_20150114_0954... OK
taiga_1     |   Applying issues.0005_auto_20150623_1923... OK
taiga_1     |   Applying issues.0006_remove_issue_watchers... OK
taiga_1     |   Applying projects.0046_triggers_to_update_tags_colors... OK
taiga_1     |   Applying projects.0047_auto_20160614_1201... OK
taiga_1     |   Applying projects.0048_auto_20160615_1508... OK
taiga_1     |   Applying projects.0049_auto_20160629_1443... OK
taiga_1     |   Applying projects.0050_project_epics_csv_uuid... OK
taiga_1     |   Applying userstories.0012_auto_20160614_1201... OK
taiga_1     |   Applying wiki.0001_initial... OK
taiga_1     |   Applying wiki.0002_remove_wikipage_watchers... OK
taiga_1     |   Applying wiki.0003_auto_20160615_0721... OK
taiga_1     |   Applying users.0011_user_theme... OK
taiga_1     |   Applying users.0012_auto_20150812_1142... OK
taiga_1     |   Applying users.0013_auto_20150901_1600... OK
taiga_1     |   Applying users.0014_auto_20151005_1357... OK
taiga_1     |   Applying users.0015_auto_20160120_1409... OK
taiga_1     |   Applying users.0016_auto_20160204_1050... OK
taiga_1     |   Applying users.0017_auto_20160208_1751... OK
taiga_1     |   Applying users.0018_remove_vote_issues_in_roles_permissions_field... OK
taiga_1     |   Applying users.0019_auto_20160519_1058... OK
taiga_1     |   Applying users.0020_auto_20160525_1229... OK
taiga_1     |   Applying users.0021_auto_20160614_1201... OK
taiga_1     |   Applying users.0022_auto_20160629_1443... OK
taiga_1     |   Applying history.0005_auto_20141120_1119... OK
taiga_1     |   Applying history.0006_fix_json_field_not_null... OK
taiga_1     |   Applying history.0007_set_bloked_note_and_is_blocked_in_snapshots... OK
taiga_1     |   Applying history.0008_auto_20150508_1028... OK
taiga_1     |   Applying history.0009_auto_20160512_1110... OK
taiga_1     |   Applying history.0010_historyentry_project... OK
taiga_1     |   Applying history.0011_auto_20160629_1036... OK
taiga_1     |   Applying history.0012_auto_20160629_1036... OK
taiga_1     |   Applying epics.0001_initial... OK
taiga_1     |   Applying epics.0002_epic_color... OK
taiga_1     |   Applying custom_attributes.0001_initial... OK
taiga_1     |   Applying custom_attributes.0002_issuecustomattributesvalues_taskcustomattributesvalues_userstorycustomattributesvalues... OK
taiga_1     |   Applying custom_attributes.0003_triggers_on_delete_customattribute... OK
taiga_1     |   Applying custom_attributes.0004_create_empty_customattributesvalues_for_existen_object... OK
taiga_1     |   Applying custom_attributes.0005_auto_20150505_1639... OK
taiga_1     |   Applying custom_attributes.0006_auto_20151014_1645... OK
taiga_1     |   Applying custom_attributes.0007_auto_20160208_1751... OK
taiga_1     |   Applying custom_attributes.0008_auto_20160728_0540... OK
taiga_1     |   Applying custom_attributes.0009_auto_20160728_1002... OK
taiga_1     |   Applying custom_attributes.0010_auto_20160928_0540... OK
taiga_1     |   Applying djmail.0001_initial... OK
taiga_1     |   Applying easy_thumbnails.0001_initial... OK
taiga_1     |   Applying easy_thumbnails.0002_thumbnaildimensions... OK
taiga_1     |   Applying epics.0003_auto_20160901_1021... OK
taiga_1     |   Applying epics.0004_auto_20160928_0540... OK
taiga_1     |   Applying external_apps.0001_initial... OK
taiga_1     |   Applying external_apps.0002_remove_application_key... OK
taiga_1     |   Applying feedback.0001_initial... OK
taiga_1     |   Applying github.0001_initial... OK
taiga_1     |   Applying gitlab.0001_initial... OK
taiga_1     |   Applying gitlab.0002_auto_20150703_1102... OK
taiga_1     |   Applying gogs.0001_initial... OK
taiga_1     |   Applying history.0013_historyentry_values_diff_cache... OK
taiga_1     |   Applying issues.0007_auto_20160614_1201... OK
taiga_1     |   Applying likes.0002_auto_20151130_2230... OK
taiga_1     |   Applying milestones.0002_remove_milestone_watchers... OK
taiga_1     |   Applying notifications.0005_auto_20151005_1357... OK
taiga_1     |   Applying notifications.0006_auto_20151103_0954... OK
taiga_1     |   Applying projects.0051_auto_20160729_0802... OK
taiga_1     |   Applying projects.0052_epic_status... OK
taiga_1     |   Applying projects.0053_auto_20160927_0741... OK
taiga_1     |   Applying projects.0054_auto_20160928_0540... OK
taiga_1     |   Applying references.0001_initial... OK
taiga_1     |   Applying sessions.0001_initial... OK
taiga_1     |   Applying taiga_contrib_slack.0001_initial... OK
taiga_1     |   Applying taiga_contrib_slack.0002_slackhook_channel... OK
taiga_1     |   Applying taiga_contrib_slack.0003_auto_20150923_1620... OK
taiga_1     |   Applying taiga_contrib_slack.0004_auto_20160914_1420... OK
taiga_1     |   Applying tasks.0010_auto_20160614_1201... OK
taiga_1     |   Applying tasks.0011_auto_20160928_0755... OK
taiga_1     |   Applying timeline.0005_auto_20160706_0723... OK
taiga_1     |   Applying userstorage.0001_initial... OK
taiga_1     |   Applying userstorage.0002_fix_json_field_not_null... OK
taiga_1     |   Applying userstories.0013_auto_20160722_1018... OK
taiga_1     |   Applying userstories.0014_auto_20160928_0540... OK
taiga_1     |   Applying votes.0001_initial... OK
taiga_1     |   Applying votes.0002_auto_20150805_1600... OK
taiga_1     |   Applying webhooks.0001_initial... OK
taiga_1     |   Applying webhooks.0002_webhook_name... OK
taiga_1     |   Applying webhooks.0003_auto_20150122_1021... OK
taiga_1     |   Applying webhooks.0004_auto_20150202_0834... OK
taiga_1     |   Applying webhooks.0005_auto_20150505_1639... OK
taiga_1     |   Applying wiki.0004_auto_20160928_0540...Trying import local.py settings...
taiga_1     |  OK
taiga_1     | Trying import local.py settings...
taiga_1     | Installed 1 object(s) from 1 fixture(s)
taiga_1     | Trying import local.py settings...
taiga_1     | Installed 2 object(s) from 1 fixture(s)
taiga_1     | Trying import local.py settings...
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/fr/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/pl/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/fi/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/pt_BR/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/it/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/sv/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/tr/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/nl/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/ru/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/es/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/ca/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/nb/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/de/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/en/LC_MESSAGES
taiga_1     | processing file django.po in /usr/src/taiga-back/taiga/locale/zh-Hant/LC_MESSAGES
taiga_1     | Trying import local.py settings...
```
This is the point where the process hangs and visiting `localhost` with a browser sometimes results in a white page. Only the favicon is loaded correctly. The console logs a request from the browser.

I sometimes also got it to start loading a site from Taiga, but then it would display an error page. (Along the lines of: Something went wrong, our Oompa Loompas are on it.) The console logs some requests from the browser.  
I don't know how to reproduce this latter behaviour, though...

Interestingly I can get the latter behaviour also on my Xubuntu laptop, so this does not seem to be entirely a Windows problem.

Do you have any clue as to what is going on? This might also be multiple distinct issues, that could maybe be better addressed individually.

**Comment by sjoerd222888** [comment]
Did you make sure you add the correct host in conftaiga/conf.json. If you see localhost for the api URL it will only be able to access Taiga from the host running the container. You should configure the proper URL of the server or change the line to

` "api": "http://TAIGA_HOSTNAME/api/v1/"`

then it will take over what you have configured in the docker-compose.yml file.

**Comment by asnikitin** [comment]
I have similar issue, when build container with -p 8001:80
First check that -p 80:80
Second check TAIGA_HOSTNAME.
You client will request api ${TAIGA_HOSTNAME}/api/v1
if you deploy taiga anywhere in network (including vbox with own ip address) `localhost` will not works
