### ISSUE TITLE
Docker-compose ps shows the state is exit no up

### ISSUE THREAD

**Issue by naivewen** [benhutchins/docker-taiga-example#11]
Docker-compose ps shows the state is exit no up,how can I fix?

**Comment by benhutchins** [comment]
Try running `docker-compose logs` to see what is failing

**Comment by naivewen** [comment]
OK,I try to find something wrong,thank you!

**Comment by naivewen** [comment]
I find the wrong log like this:

taiga_1     | Traceback (most recent call last):
taiga_1     |   File "/checkdb.py", line 14, in <module>
taiga_1     |     conn = psycopg2.connect(conn_string)
taiga_1     |   File "/usr/local/lib/python3.5/site-packages/psycopg2/__init__.py", line 130, in connect
taiga_1     |     conn = _connect(dsn, connection_factory=connection_factory, **                                kwasync)
taiga_1     | psycopg2.OperationalError: could not connect to server: Connection                                 refused
taiga_1     |   Is the server running on host "postgres" (172.18.0.2) and accepting
taiga_1     |   TCP/IP connections on port 5432?
taiga_1     |
taiga_1     | Failed to connect to database server or database does not exist.

How can I fix it?

**Comment by ajthyng** [comment]
If you run `docker-compose up -d` a second time the front end container should come up and successfully connect to the database. I get the same error. Not knowing much about docker-compose I'm assuming the front-end is trying to connect to the back-end before it's done starting up.
