### ISSUE TITLE
docker-compose up exits with error

### ISSUE THREAD

**Issue by ecomovement** [benhutchins/docker-taiga-example#16]
```
Step 5/7 : RUN SLACK_VERSION=$(pip show taiga-contrib-slack | awk '/^Version: /{print $2}') &&     echo "taiga-contrib-slack version: $SLACK_VERSION" &&     curl https://raw.githubusercontent.com/taigaio/taiga-contrib-slack/$SLACK_VERSION/front/dist/slack.js -o /usr/src/taiga-front-dist/dist/plugins/slack/slack.js &&     curl https://raw.githubusercontent.com/taigaio/taiga-contrib-slack/$SLACK_VERSION/front/dist/slack.json -o /usr/src/taiga-front-dist/dist/plugins/slack/slack.json
 ---> Running in 2e4d807426fd
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/logging/__init__.py", line 988, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\xfa' in position 11: ordinal not in range(128)
Call stack:
  File "/usr/local/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/pip/__init__.py", line 233, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/site-packages/pip/commands/show.py", line 42, in run
    results, list_files=options.files, verbose=options.verbose):
  File "/usr/local/lib/python3.5/site-packages/pip/commands/show.py", line 133, in print_results
    logger.info("Author: %s", dist.get('author', ''))
Message: 'Author: %s'
Arguments: ('Jes\xfas Espino Garc\xeda',)
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by Robert-turbo** [comment]
I have the same error. 
Did you manage to resolve this issue?

**Comment by astamiviswakarma** [comment]
I have got similar error 
```--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/logging/__init__.py", line 988, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\xfa' in position 11: ordinal not in range(128)
Call stack:
  File "/usr/local/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/pip/__init__.py", line 233, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/site-packages/pip/commands/show.py", line 42, in run
    results, list_files=options.files, verbose=options.verbose):
  File "/usr/local/lib/python3.5/site-packages/pip/commands/show.py", line 133, in print_results
    logger.info("Author: %s", dist.get('author', ''))
Message: 'Author: %s'
Arguments: ('Jes\xfas Espino Garc\xeda',)
You are using pip version 9.0.1, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
